server:
  port: 8082

spring:
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG


security:
  oauth2:
    client:
      registration:
        google:
          provider: google
          clientId: 39681820339-pl5lo8969v8s92fkbpt9agasf8dss8t4.apps.googleusercontent.com
          clientSecret: nVCInr8peTsWL1lElpZSHSsq
          client-authentication-method: basic
          authorization-grant-type: authorization_code
          scope:
            - email
            - profile
      provider:
        google:
          issuer-uri: https://accounts.google.com