
logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            clientId: 39681820339-pl5lo8969v8s92fkbpt9agasf8dss8t4.apps.googleusercontent.com
            clientSecret: nVCInr8peTsWL1lElpZSHSsq
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/tasks.readonly
        provider:
          google:
            issuer-uri: https://accounts.google.com